services:
  - type: web
    name: xeno-crm-backend
    env: node
    region: oregon # or any region you prefer
    plan: free
    buildCommand: "npm install"
    startCommand: "npm run start"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
